name: AutoQuotePoster

on:
  schedule:
    - cron: '0 22,10 * * *'  # Runs 6 AM & 6 PM PH time (UTC+8)
  workflow_dispatch:         # Optional: lets you run it manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the poster script
        env:
          FB_PAGE_ID:     ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_TOKEN:  ${{ secrets.FB_ACCESS_TOKEN }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py
